### ISSUE TITLE
dji-moonlight-gui for linux?

### ISSUE THREAD

**Issue by snigel** [fpv-wtf/dji-moonlight-gui#2]
Would be really cool to pair the goggles to a steamdeck, but the gui app seems to be Windows only?

**Comment by jonboy86** [comment]
i second that would be awesome for deck users

**Comment by j005u** [comment]
The GUI relies on Microsoft's Webview2 which is not available for Linux.

Here's where I got to for building a flatpak for the CLI app at one point -

wtf.fpv.moonlight-embedded.yaml
```
app-id: wtf.fpv.moonlight-embedded
runtime: org.freedesktop.Platform
runtime-version: '22.08'
sdk: org.freedesktop.Sdk
command: moonlight
finish-args:
- --share=network
- --device=all
modules:
- name: libusb
  config-opts:
  - --disable-static
  - --disable-udev
  cleanup:
  - "/lib/*.la"
  - "/lib/pkgconfig"
  - "/include"
  sources:
  - type: archive
    url: https://github.com/libusb/libusb/archive/v1.0.22.tar.gz
    sha256: 3500f7b182750cd9ccf9be8b1df998f83df56a39ab264976bdb3307773e16f48
  post-install:
  - install -Dm644 COPYING /app/share/licenses/libusb/COPYING
- name: moonlight
  sources:
  - type: git
    url: https://github.com/fpv-wtf/dji-moonlight-embedded.git
    branch: main
  buildsystem: cmake
  config-opts:
  - "-DCMAKE_BUILD_TYPE=Release"
```
For building on Ubuntu:
```
sudo apt install flatpak flatpak-builder
flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08
git config --global --add protocol.file.allow always

flatpak-builder --user --install --force-clean build wtf.fpv.moonlight-embedded.yaml
flatpak run wtf.fpv.moonlight-embedded
```
Said flatpak _should_ work on the Steam Deck. You may need to:
```
mdkir -p ~/.var/app/wtf.fpv.moonlight-embedded
cd  ~/.var/app/wtf.fpv.moonlight-embedded
```
before running it because I didn't bother fixing up the paths used for pairing info storage. Unclear if it's necessary, I don't have a Deck to test with.

No time to polish or publish this, but glhf to anyone that would like to do so.
